### ISSUE TITLE
JavaScript runtime exception when using dojobuild with 1.7.*

### ISSUE THREAD

**Issue by zimnyx** [klipstein/dojango#98]
I tried it on both 1.7.0 and 1.7.1.
Does it work for you?

python manage.py dojoload --dojo_version 1.7.0
python manage.py dojobuild 
Usage: java [-options] class [args...](to execute a class)
   or  java [-options] -jar jarfile [args...](to execute a jar file)
where options include:
    -d32      use a 32-bit data model if available
    -d64      use a 64-bit data model if available
    -server   to select the "server" VM
    -jamvm    to select the "jamvm" VM
    -cacao    to select the "cacao" VM
    -zero     to select the "zero" VM
    -shark    is a synonym for the "zero" VM  [deprecated]
                  The default VM is server.

```
-cp <class search path of directories and zip/jar files>
-classpath <class search path of directories and zip/jar files>
              A : separated list of directories, JAR archives,
              and ZIP archives to search for class files.
-D<name>=<value>
              set a system property
-verbose[:class|gc|jni]
              enable verbose output
-version      print product version and exit
-version:<value>
              require the specified version to run
-showversion  print product version and continue
-jre-restrict-search | -jre-no-restrict-search
              include/exclude user private JREs in the version search
-? -help      print this help message
-X            print help on non-standard options
-ea[:<packagename>...|:<classname>]
-enableassertions[:<packagename>...|:<classname>]
              enable assertions with specified granularity
-da[:<packagename>...|:<classname>]
-disableassertions[:<packagename>...|:<classname>]
              disable assertions with specified granularity
-esa | -enablesystemassertions
              enable system assertions
-dsa | -disablesystemassertions
              disable system assertions
-agentlib:<libname>[=<options>]
              load native agent library <libname>, e.g. -agentlib:hprof
              see also, -agentlib:jdwp=help and -agentlib:hprof=help
-agentpath:<pathname>[=<options>]
              load native agent library by full pathname
-javaagent:<jarpath>[=<options>]
              load Java programming language agent, see java.lang.instrument
-splash:<imagepath>
              show splash screen with specified image
```

See http://java.sun.com/javase/reference for more details.
warn(218) the command line switch profileFile is deprectated; use profile for both files and profiles 
processing profile resource /tmp/proj/dojo/my.profile.js
js: "<eval'ed string>#1(Function)#1(eval)", line 207: uncaught JavaScript runtime exception: TypeError: Cannot call property log in object [object Object]. It is not a function, it is "number".
    at <eval'ed string>#1(Function)#1(eval):207 (processPackage)
    at <eval'ed string>#1(Function)#1(eval):289
    at <eval'ed string>#1(Function)#1(eval):191
    at <eval'ed string>#1(Function)#1(eval):84

**Comment by klipstein** [comment]
Just tried it here and Dojo 1.7.2 built succesfully. I'm wondering on what system you've executed that command, especially that you get some java output? I've tested it on Mac OS X and could retry it with an Ubuntu Linux.

**Comment by zimnyx** [comment]
Forgive me, my mistake. After upgrade to 1.7.\* allowed build script parameters have changed - and I haven't updated my code -  that was only reason.
It's all working just fine, please close.
