### ISSUE TITLE
63 - Does not work with Django < 1.2 alpha 1 

### ISSUE THREAD

**Issue by klipstein** [klipstein/dojango#63]
<pre>
<b>What steps will reproduce the problem?</b>
1. Create a project with Django version &lt; 1.2 alpha 1
2. Install Dojango on it
3. Execute: python manage.py shell
4. At shell, execute: &gt;&gt;&gt; import dojango.forms

<b>What is the expected output? What do you see instead?</b>

It should work, since Project Home of Dojango sayd: 
_Dojango 0.4: the <a title="Help - How to enable Dojo's form functionality in dojango." href="/p/dojango/wiki/FormIntegration">FormIntegration</a> just works with Django &gt;= 1.0.2_

But that occurs: 

Traceback (most recent call last):
  File &quot;&lt;ipython console&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/alanjds/src/hg/Delinear_fabrica/projdelinear/dojango/forms/**init**.py&quot;, line 3, in &lt;module&gt;
    from fields import *
  File &quot;/home/alanjds/src/hg/Delinear_fabrica/projdelinear/dojango/forms/fields.py&quot;, line 3, in &lt;module&gt;
    from django.utils import formats
ImportError: cannot import name formats

<b>What version of the product are you using? On what operating system?</b>

Tested using Dojango 0.5.1 and Django 1.1.0 final on CPython 2.6.4

<b>Please provide any additional information below.</b>

Is there a way to run at Django &lt; 1.2? If not, please update Project Home.

</pre></br>Original link: http://code.google.com/p/dojango/issues/detail?id=63
